### ISSUE TITLE
role played by each individual group member

### ISSUE THREAD

**Issue by tristaaan** [diegocasmo/iis-project#44]

**Comment by diegocasmo** [comment]
Not even sure what to put here?

**Comment by tristaaan** [comment]
Hadn't we started writing this somewhere?

-Tristan Wright

**Comment by tristaaan** [comment]
Wait it is, yes. Final section of the introduction, sorry.

**Comment by tristaaan** [comment]
Or wait, it's not "contributions" ?? We could just toss in something, merge with the next section, or skip it

**Comment by ankurshukla03** [comment]
Final section of Introdcution is Group Members Contribution and we have one more section as Role Played by Group Members.

**Comment by ankurshukla03** [comment]
- Kalyan said in his mail that difference between Role and Contributor is
- Role: Developer/Tester/Integrator etc
- Contribution: Coding (what modules you have coded), how many test setups you have tested and development changes you had to make due to these scenarios, web site creations etc

For Parsing lm2 Diego as developer and Tristan for lm3 as developer
KNN and SVM Diego as a developer and tristan as a Testor
MLP Tristan developer and Ankur Tester
Random Forest Ankur developer and Tristan Testor
Final Integration of all the models and the best run generated by Diego
Just a rough idea ?

**Comment by tristaaan** [comment]
We're all developers and implementors,
Chief architects of vision and deployment,
Lead sales and task designators,
Senior clairvoyant prognosticators


-Tristan Wright

**Comment by ankurshukla03** [comment]
I am just making up stuff as he replied me in the mail but still both of the sections in introduction doesn't make much sense.

**Comment by diegocasmo** [comment]
But we still need to specify it in the report, right (it's a mandatory section)?

**Comment by ankurshukla03** [comment]
Yes that's why i was making up the stuff. From Kalyan reply it seems mandatory.

**Comment by tristaaan** [comment]
We're all developers and integrators

```
\begin{itemize}
\item Diego Castillo: developer and integrator
\item Ankur Shukla: developer and integrator
\item Tristan Wright: developer and integrator
\end{itemize}
```

-Tristan Wright
